### ISSUE TITLE
Russian voices

### ISSUE THREAD

**Issue by romkazor** [Idlak/idlak#133]
Hello, where is russian voices?!

Where I can find from [docs](https://idlak.readthedocs.io/en/latest/rest_server.html):

`./seed/addvoice.py -g female -n Anastasia -i abr -d ../idlak-egs/tts_tangle_idlak/s2/voices/ru/ru/abr_pmdl`

tts_tangle_idlak and ru folders is missing.

Thanks.

**Comment by dabraude** [comment]
That assumes you have trained the model yourself. 
When I find some time I can upload a pre-trained model.

**Comment by dabraude** [comment]
Docs have been updated with the correct location in the Readme file
